[package]
name = "updater"
version = "0.1.0"
authors = ["Dustin Carlino <dabreegster@gmail.com>"]
edition = "2018"

[dependencies]
abstio = { path = "../abstio" }
abstutil = { path = "../abstutil" }
anyhow = "1.0.38"
flate2 = "1.0.20"
geom = { path = "../geom" }
md5 = "0.7.0"
reqwest = { version = "0.11.0", default-features=false, features=["rustls-tls"] }
tokio = { version = "1.1.1", features = ["full"] }
walkdir = "2.3.1"
